apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nutritious-cricket-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nutritious-cricket-java-quarkus-gitops